"""Add unique contraint for Source table

Revision ID: aeae21b2e3b4
Revises: 9f3feb6e011b
Create Date: 2023-12-06 01:33:08.452360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aeae21b2e3b4"
down_revision: Union[str, None] = "9f3feb6e011b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("unique_source", "sources", ["film_id", "title"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_source", "sources", type_="unique")
    # ### end Alembic commands ###
